//! DO NOT EDIT!
//! This file is automatically generated by the script in the canonical
//! SQLite source tree at tool/mkctimec.tcl.
//!
//! To modify this header, edit any of the various lists in that script
//! which specify categories of generated conditionals in this file.
#[repr(C, align(16))]
struct __SlateAlign16<T>(T);

// 2010 February 23
//
// The author disclaims copyright to this source code.  In place of
// a legal notice, here is a blessing:
//
//    May you do good and not evil.
//    May you find forgiveness for yourself and forgive others.
//    May you share freely, never taking more than you give.
//
//
//
// This file implements routines used to report what compile-time options
// SQLite was built with.
// Include the configuration header output by 'configure' if we're using the
// autoconf-based build
// These macros are provided to "stringify" the value of the define
// for those options in which the value is meaningful.
// Like CTIMEOPT_VAL, but especially for SQLITE_DEFAULT_LOOKASIDE. This
// option requires a separate macro because legal values contain a single
// comma. e.g. (-DSQLITE_DEFAULT_LOOKASIDE="100,100")
// An array of names of all compile-time options.  This array should
// be sorted A-Z.
//
// This array looks large, but in a typical installation actually uses
// only a handful of compile-time options, so most times this array is usually
// rather short and uses little memory space.
static mut sqlite3azCompileOpt: __SlateAlign16<[*const i8; 53]> = __SlateAlign16([
    (b"ATOMIC_INTRINSICS=1\0".as_ptr() as *mut i8) as *const i8,
    (b"COMPILER=clang-22.1.8\0".as_ptr() as *mut i8) as *const i8,
    (b"DEFAULT_AUTOVACUUM\0".as_ptr() as *mut i8) as *const i8,
    (b"DEFAULT_CACHE_SIZE=-2000\0".as_ptr() as *mut i8) as *const i8,
    (b"DEFAULT_FILE_FORMAT=4\0".as_ptr() as *mut i8) as *const i8,
    (b"DEFAULT_JOURNAL_SIZE_LIMIT=-1\0".as_ptr() as *mut i8) as *const i8,
    (b"DEFAULT_MMAP_SIZE=0\0".as_ptr() as *mut i8) as *const i8,
    (b"DEFAULT_PAGE_SIZE=4096\0".as_ptr() as *mut i8) as *const i8,
    (b"DEFAULT_PCACHE_INITSZ=20\0".as_ptr() as *mut i8) as *const i8,
    (b"DEFAULT_RECURSIVE_TRIGGERS\0".as_ptr() as *mut i8) as *const i8,
    (b"DEFAULT_SECTOR_SIZE=4096\0".as_ptr() as *mut i8) as *const i8,
    (b"DEFAULT_SYNCHRONOUS=2\0".as_ptr() as *mut i8) as *const i8,
    (b"DEFAULT_WAL_AUTOCHECKPOINT=1000\0".as_ptr() as *mut i8) as *const i8,
    (b"DEFAULT_WAL_SYNCHRONOUS=2\0".as_ptr() as *mut i8) as *const i8,
    (b"DEFAULT_WORKER_THREADS=0\0".as_ptr() as *mut i8) as *const i8,
    (b"DIRECT_OVERFLOW_READ\0".as_ptr() as *mut i8) as *const i8,
    (b"DQS=0\0".as_ptr() as *mut i8) as *const i8,
    (b"ENABLE_BYTECODE_VTAB\0".as_ptr() as *mut i8) as *const i8,
    (b"ENABLE_DBPAGE_VTAB\0".as_ptr() as *mut i8) as *const i8,
    (b"ENABLE_DBSTAT_VTAB\0".as_ptr() as *mut i8) as *const i8,
    (b"ENABLE_EXPLAIN_COMMENTS\0".as_ptr() as *mut i8) as *const i8,
    (b"ENABLE_FTS3\0".as_ptr() as *mut i8) as *const i8,
    (b"ENABLE_FTS4\0".as_ptr() as *mut i8) as *const i8,
    (b"ENABLE_MATH_FUNCTIONS\0".as_ptr() as *mut i8) as *const i8,
    (b"ENABLE_OFFSET_SQL_FUNC\0".as_ptr() as *mut i8) as *const i8,
    (b"ENABLE_PERCENTILE\0".as_ptr() as *mut i8) as *const i8,
    (b"ENABLE_RTREE\0".as_ptr() as *mut i8) as *const i8,
    (b"ENABLE_STMTVTAB\0".as_ptr() as *mut i8) as *const i8,
    (b"ENABLE_UNKNOWN_SQL_FUNCTION\0".as_ptr() as *mut i8) as *const i8,
    (b"HAVE_ISNAN\0".as_ptr() as *mut i8) as *const i8,
    (b"MALLOC_SOFT_LIMIT=1024\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_ATTACHED=10\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_COLUMN=2000\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_COMPOUND_SELECT=500\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_DEFAULT_PAGE_SIZE=8192\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_EXPR_DEPTH=1000\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_FUNCTION_ARG=1000\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_LENGTH=1000000000\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_LIKE_PATTERN_LENGTH=50000\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_MMAP_SIZE=0x7fff0000\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_PAGE_COUNT=0xfffffffe\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_PAGE_SIZE=65536\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_SCHEMA=10000000\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_SQL_LENGTH=1000000000\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_TRIGGER_DEPTH=1000\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_VARIABLE_NUMBER=32766\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_VDBE_OP=250000000\0".as_ptr() as *mut i8) as *const i8,
    (b"MAX_WORKER_THREADS=8\0".as_ptr() as *mut i8) as *const i8,
    (b"MUTEX_PTHREADS\0".as_ptr() as *mut i8) as *const i8,
    (b"STRICT_SUBTYPE\0".as_ptr() as *mut i8) as *const i8,
    (b"SYSTEM_MALLOC\0".as_ptr() as *mut i8) as *const i8,
    (b"TEMP_STORE=1\0".as_ptr() as *mut i8) as *const i8,
    (b"THREADSAFE=1\0".as_ptr() as *mut i8) as *const i8,
]);

#[unsafe(no_mangle)]
extern "C-unwind" fn sqlite3CompileOptions(mut pnOpt: *mut i32) -> *mut *const i8 {
    unsafe {
        *pnOpt = (((424 as u64) / (8 as u64)) as u32) as i32;
    }
    return (unsafe { std::ptr::addr_of!(sqlite3azCompileOpt.0) as *const *const i8 })
        as *mut *const i8;
}
