// /*
// ** 2006 Oct 10
// **
// ** The author disclaims copyright to this source code.  In place of
// ** a legal notice, here is a blessing:
// **
// **    May you do good and not evil.
// **    May you find forgiveness for yourself and forgive others.
// **    May you share freely, never taking more than you give.
// **
// ******************************************************************************
// **
// ** This is an SQLite module implementing full-text search.
// */
// /*
// ** The code in this file is only compiled if:
// **
// **     * The FTS3 module is being built as an extension
// **       (in which case SQLITE_CORE is not defined), or
// **
// **     * The FTS3 module is being built into the core of
// **       SQLite (in which case SQLITE_ENABLE_FTS3 is defined).
// */
// /* The full-text index is stored in a series of b+tree (-like)
// ** structures called segments which map terms to doclists.  The
// ** structures are like b+trees in layout, but are constructed from the
// ** bottom up in optimal fashion and are not updatable.  Since trees
// ** are built from the bottom up, things will be described from the
// ** bottom up.
// **
// **
// **** Varints ****
// ** The basic unit of encoding is a variable-length integer called a
// ** varint.  We encode variable-length integers in little-endian order
// ** using seven bits * per byte as follows:
// **
// ** KEY:
// **         A = 0xxxxxxx    7 bits of data and one flag bit
// **         B = 1xxxxxxx    7 bits of data and one flag bit
// **
// **  7 bits - A
// ** 14 bits - BA
// ** 21 bits - BBA
// ** and so on.
// **
// ** This is similar in concept to how sqlite encodes "varints" but
// ** the encoding is not the same.  SQLite varints are big-endian
// ** are are limited to 9 bytes in length whereas FTS3 varints are
// ** little-endian and can be up to 10 bytes in length (in theory).
// **
// ** Example encodings:
// **
// **     1:    0x01
// **   127:    0x7f
// **   128:    0x81 0x00
// **
// **
// **** Document lists ****
// ** A doclist (document list) holds a docid-sorted list of hits for a
// ** given term.  Doclists hold docids and associated token positions.
// ** A docid is the unique integer identifier for a single document.
// ** A position is the index of a word within the document.  The first
// ** word of the document has a position of 0.
// **
// ** FTS3 used to optionally store character offsets using a compile-time
// ** option.  But that functionality is no longer supported.
// **
// ** A doclist is stored like this:
// **
// ** array {
// **   varint docid;          (delta from previous doclist)
// **   array {                (position list for column 0)
// **     varint position;     (2 more than the delta from previous position)
// **   }
// **   array {
// **     varint POS_COLUMN;   (marks start of position list for new column)
// **     varint column;       (index of new column)
// **     array {
// **       varint position;   (2 more than the delta from previous position)
// **     }
// **   }
// **   varint POS_END;        (marks end of positions for this document.
// ** }
// **
// ** Here, array { X } means zero or more occurrences of X, adjacent in
// ** memory.  A "position" is an index of a token in the token stream
// ** generated by the tokenizer. Note that POS_END and POS_COLUMN occur
// ** in the same logical place as the position element, and act as sentinels
// ** ending a position list array.  POS_END is 0.  POS_COLUMN is 1.
// ** The positions numbers are not stored literally but rather as two more
// ** than the difference from the prior position, or the just the position plus
// ** 2 for the first position.  Example:
// **
// **   label:       A B C D E  F  G H   I  J K
// **   value:     123 5 9 1 1 14 35 0 234 72 0
// **
// ** The 123 value is the first docid.  For column zero in this document
// ** there are two matches at positions 3 and 10 (5-2 and 9-2+3).  The 1
// ** at D signals the start of a new column; the 1 at E indicates that the
// ** new column is column number 1.  There are two positions at 12 and 45
// ** (14-2 and 35-2+12).  The 0 at H indicate the end-of-document.  The
// ** 234 at I is the delta to next docid (357).  It has one position 70
// ** (72-2) and then terminates with the 0 at K.
// **
// ** A "position-list" is the list of positions for multiple columns for
// ** a single docid.  A "column-list" is the set of positions for a single
// ** column.  Hence, a position-list consists of one or more column-lists,
// ** a document record consists of a docid followed by a position-list and
// ** a doclist consists of one or more document records.
// **
// ** A bare doclist omits the position information, becoming an
// ** array of varint-encoded docids.
// **
// **** Segment leaf nodes ****
// ** Segment leaf nodes store terms and doclists, ordered by term.  Leaf
// ** nodes are written using LeafWriter, and read using LeafReader (to
// ** iterate through a single leaf node's data) and LeavesReader (to
// ** iterate through a segment's entire leaf layer).  Leaf nodes have
// ** the format:
// **
// ** varint iHeight;             (height from leaf level, always 0)
// ** varint nTerm;               (length of first term)
// ** char pTerm[nTerm];          (content of first term)
// ** varint nDoclist;            (length of term's associated doclist)
// ** char pDoclist[nDoclist];    (content of doclist)
// ** array {
// **                             (further terms are delta-encoded)
// **   varint nPrefix;           (length of prefix shared with previous term)
// **   varint nSuffix;           (length of unshared suffix)
// **   char pTermSuffix[nSuffix];(unshared suffix of next term)
// **   varint nDoclist;          (length of term's associated doclist)
// **   char pDoclist[nDoclist];  (content of doclist)
// ** }
// **
// ** Here, array { X } means zero or more occurrences of X, adjacent in
// ** memory.
// **
// ** Leaf nodes are broken into blocks which are stored contiguously in
// ** the %_segments table in sorted order.  This means that when the end
// ** of a node is reached, the next term is in the node with the next
// ** greater node id.
// **
// ** New data is spilled to a new leaf node when the current node
// ** exceeds LEAF_MAX bytes (default 2048).  New data which itself is
// ** larger than STANDALONE_MIN (default 1024) is placed in a standalone
// ** node (a leaf node with a single term and doclist).  The goal of
// ** these settings is to pack together groups of small doclists while
// ** making it efficient to directly access large doclists.  The
// ** assumption is that large doclists represent terms which are more
// ** likely to be query targets.
// **
// ** TODO(shess) It may be useful for blocking decisions to be more
// ** dynamic.  For instance, it may make more sense to have a 2.5k leaf
// ** node rather than splitting into 2k and .5k nodes.  My intuition is
// ** that this might extend through 2x or 4x the pagesize.
// **
// **
// **** Segment interior nodes ****
// ** Segment interior nodes store blockids for subtree nodes and terms
// ** to describe what data is stored by the each subtree.  Interior
// ** nodes are written using InteriorWriter, and read using
// ** InteriorReader.  InteriorWriters are created as needed when
// ** SegmentWriter creates new leaf nodes, or when an interior node
// ** itself grows too big and must be split.  The format of interior
// ** nodes:
// **
// ** varint iHeight;           (height from leaf level, always >0)
// ** varint iBlockid;          (block id of node's leftmost subtree)
// ** optional {
// **   varint nTerm;           (length of first term)
// **   char pTerm[nTerm];      (content of first term)
// **   array {
// **                                (further terms are delta-encoded)
// **     varint nPrefix;            (length of shared prefix with previous term)
// **     varint nSuffix;            (length of unshared suffix)
// **     char pTermSuffix[nSuffix]; (unshared suffix of next term)
// **   }
// ** }
// **
// ** Here, optional { X } means an optional element, while array { X }
// ** means zero or more occurrences of X, adjacent in memory.
// **
// ** An interior node encodes n terms separating n+1 subtrees.  The
// ** subtree blocks are contiguous, so only the first subtree's blockid
// ** is encoded.  The subtree at iBlockid will contain all terms less
// ** than the first term encoded (or all terms if no term is encoded).
// ** Otherwise, for terms greater than or equal to pTerm[i] but less
// ** than pTerm[i+1], the subtree for that term will be rooted at
// ** iBlockid+i.  Interior nodes only store enough term data to
// ** distinguish adjacent children (if the rightmost term of the left
// ** child is "something", and the leftmost term of the right child is
// ** "wicked", only "w" is stored).
// **
// ** New data is spilled to a new interior node at the same height when
// ** the current node exceeds INTERIOR_MAX bytes (default 2048).
// ** INTERIOR_MIN_TERMS (default 7) keeps large terms from monopolizing
// ** interior nodes and making the tree too skinny.  The interior nodes
// ** at a given height are naturally tracked by interior nodes at
// ** height+1, and so on.
// **
// **
// **** Segment directory ****
// ** The segment directory in table %_segdir stores meta-information for
// ** merging and deleting segments, and also the root node of the
// ** segment's tree.
// **
// ** The root node is the top node of the segment's tree after encoding
// ** the entire segment, restricted to ROOT_MAX bytes (default 1024).
// ** This could be either a leaf node or an interior node.  If the top
// ** node requires more than ROOT_MAX bytes, it is flushed to %_segments
// ** and a new root interior node is generated (which should always fit
// ** within ROOT_MAX because it only needs space for 2 varints, the
// ** height and the blockid of the previous root).
// **
// ** The meta-information in the segment directory is:
// **   level               - segment level (see below)
// **   idx                 - index within level
// **                       - (level,idx uniquely identify a segment)
// **   start_block         - first leaf node
// **   leaves_end_block    - last leaf node
// **   end_block           - last block (including interior nodes)
// **   root                - contents of root node
// **
// ** If the root node is a leaf node, then start_block,
// ** leaves_end_block, and end_block are all 0.
// **
// **
// **** Segment merging ****
// ** To amortize update costs, segments are grouped into levels and
// ** merged in batches.  Each increase in level represents exponentially
// ** more documents.
// **
// ** New documents (actually, document updates) are tokenized and
// ** written individually (using LeafWriter) to a level 0 segment, with
// ** incrementing idx.  When idx reaches MERGE_COUNT (default 16), all
// ** level 0 segments are merged into a single level 1 segment.  Level 1
// ** is populated like level 0, and eventually MERGE_COUNT level 1
// ** segments are merged to a single level 2 segment (representing
// ** MERGE_COUNT^2 updates), and so on.
// **
// ** A segment merge traverses all segments at a given level in
// ** parallel, performing a straightforward sorted merge.  Since segment
// ** leaf nodes are written in to the %_segments table in order, this
// ** merge traverses the underlying sqlite disk structures efficiently.
// ** After the merge, all segment blocks from the merged level are
// ** deleted.
// **
// ** MERGE_COUNT controls how often we merge segments.  16 seems to be
// ** somewhat of a sweet spot for insertion performance.  32 and 64 show
// ** very similar performance numbers to 16 on insertion, though they're
// ** a tiny bit slower (perhaps due to more overhead in merge-time
// ** sorting).  8 is about 20% slower than 16, 4 about 50% slower than
// ** 16, 2 about 66% slower than 16.
// **
// ** At query time, high MERGE_COUNT increases the number of segments
// ** which need to be scanned and merged.  For instance, with 100k docs
// ** inserted:
// **
// **    MERGE_COUNT   segments
// **       16           25
// **        8           12
// **        4           10
// **        2            6
// **
// ** This appears to have only a moderate impact on queries for very
// ** frequent terms (which are somewhat dominated by segment merge
// ** costs), and infrequent and non-existent terms still seem to be fast
// ** even with many segments.
// **
// ** TODO(shess) That said, it would be nice to have a better query-side
// ** argument for MERGE_COUNT of 16.  Also, it is possible/likely that
// ** optimizations to things like doclist merging will swing the sweet
// ** spot around.
// **
// **
// **
// **** Handling of deletions and updates ****
// ** Since we're using a segmented structure, with no docid-oriented
// ** index into the term index, we clearly cannot simply update the term
// ** index when a document is deleted or updated.  For deletions, we
// ** write an empty doclist (varint(docid) varint(POS_END)), for updates
// ** we simply write the new doclist.  Segment merges overwrite older
// ** data for a particular docid with newer data, so deletes or updates
// ** will eventually overtake the earlier data and knock it out.  The
// ** query logic likewise merges doclists so that newer data knocks out
// ** older data.
// */
